"""empty message

Revision ID: e41f1d890188
Revises: 4a15877a67bb
Create Date: 2024-07-06 18:03:16.231041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41f1d890188'
down_revision = '4a15877a67bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('_class')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_class', sa.VARCHAR(length=40), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
